### ISSUE TITLE
Buenisimo, pero el poligono geo?

### ISSUE THREAD

**Issue by vlasvlasvlas** [jcodagnone/localidades-ar#1]
Hola, esta buenisimo!

Estoy buscando la forma de generar o tomar los polígonos de localidades del país para después asignarle los códigos postales y tenes llegar a los polígonos de códigos postales del país. 

Pero si bien encuentro tablas de números de cp  y localidades, no logro dar con polígonos de localidades a nivel país. sabes si existen o si alguien los tiene?

gracias!

**Comment by vlasvlasvlas** [comment]
https://github.com/vlasvlasvlas/codigospostales ;)

**Comment by jcodagnone** [comment]
buenisimo: dejé un comentarion en el README.md https://github.com/jcodagnone/localidades-ar/commit/efdfb0d709b5e936fbfe7ceaafb347e2e20067fd
