### ISSUE TITLE
Not Found https://github.com/vlasvlasvlas/codigospostales

### ISSUE THREAD

**Issue by AugPav** [jcodagnone/localidades-ar#3]
Hola,

No esta el proyecto  https://github.com/vlasvlasvlas/codigospostales/ .

Lo podrías subir?

Gracias

**Comment by jcodagnone** [comment]
Hola, 

El repositorio ese seguramente fue borrado por el autor. Yo no tengo ninguna copia (de hecho no  lo conocía). Se lo tenés que pedir a  https://github.com/vlasvlasvlas/.

Saludos,
 Juan.
